blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
"""Определяет схемы URL для blogs."""
from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    # Страница со списком всех блогов
    path('blogs/', views.blogs, name='blogs'),
    # Страница с подробной информацией по отдельному блогу
    path('blogs/<int:blog_id>/', views.blog, name='blog'),
    # Страница для добавления нового блога
    path('new_blog/', views.new_blog, name='new_blog'),
    # Страница для добавления новой записи
    path('new_entry/<int:blog_id>', views.new_entry, name='new_entry'),
    # Странца для редактирования записи
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Определяет схемы URL для пользователей"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Включить URL авторизации по умолчанию
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class BlogPost(models.Model):
    """Блог, который ведёт пользователь."""
    text = models.CharField(max_length=350)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        """Возвращает строковое представление модели."""
        return self.text

class Entry(models.Model):
    """Информация, представленная пользователем в блоге."""
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        """Возвращает строковое представление модели."""
        if len(self.text) < 101:
            return self.text
        else:
            return f"{self.text[:100]}..."

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import BlogPost, Entry

class BlogForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import BlogPost, Entry
from .forms import BlogForm, EntryForm

def index(request):
    """Домашняя страница приложения Blogs."""
    return render(request, 'blogs/index.html')

def blogs(request):
    """Выводит перечень блогов."""
    blogs = BlogPost.objects.order_by('date_added')
    context = {'blogs': blogs}
    return render(request, 'blogs/blogs.html', context)

def blog(request, blog_id):
    """Выводит один блог и все записи."""
    blog = BlogPost.objects.get(id=blog_id)
    entries = blog.entry_set.order_by('-date_added')
    context = {'blog': blog, 'entries': entries}
    return render(request, 'blogs/blog.html', context)

@login_required
def new_blog(request):
    """Определяет новый блог."""
    if request.method != 'POST':
        # Данные не отправлялись; создаётся пустая форма
        form = BlogForm()
    else:
        # Отправлены данные POST: обработать данные
        form = BlogForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blogs')

    # Вывести пустую или недействительную форму
    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)

@login_required
def new_entry(request, blog_id):
    """Добавляет новую запись по конкретному блогу."""
    blog = BlogPost.objects.get(id=blog_id)
    if request.method != 'POST':
        # Данные не отправлялись; создаётся пустая форма
        form = EntryForm()
    else:
        # Отправлены данные POST: обработать данные
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.post = blog
            new_entry.save()
            return redirect('blogs:blog', blog_id=blog_id)
    # Вывести пустую или недействительную форму
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Редактирует существующую запись."""
    entry = Entry.objects.get(id=entry_id)
    blog = entry.post
    if blog.owner != request.user:
        raise Http404
    
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = EntryForm(instance=entry)
    else:
        # Отправка данных POST; обработать данные.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect ('blogs:blog', blog_id=blog.id)
    context = {'entry': entry, 'blog': blog, 'form': form}
    return render(request, 'blogs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        # Выводит пустую форму регистрации.
        form = UserCreationForm()
    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу.
            login(request, new_user)
            return redirect('blogs:index')
    # Вывести пстую или недействительную форму.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
      shrink-to-fit=no">
    <title>Blog</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

  </head>
  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 border">

      <a class="navbar-brand" href="{% url "blogs:index" %}">
          Blog</a>
      
      <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarCollapse" aria-controls="navbarCollapse"
          aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url "blogs:blogs" %}">
                Blogs</a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text">Hello, {{ user.username }}!</span>
            </li>
            <li class="nav-item">
              <form method="post" action="{% url 'users:logout' %}" class="d-inline">
                {% csrf_token %}
                <button type="submit" class="btn btn-link nav-link" style="border: none; background: none; padding: 0.5rem 1rem;">
                  Log out
                </button>
              </form>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url "users:register" %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "users:login" %}">Log in</a></li>
          {% endif %}
        </ul>
      </div>
    
    </nav>

    <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </main>

  </body>

</html>

blogs/templates/blogs/blog.html
{% extends "blogs/base.html" %}

{% block page_header %}
  <h3>{{blog}}</h3>
{% endblock page_header %}

{% block content %}
  <p>
    <a href= "{% url "blogs:new_entry" blog.id %}">Add new entry</a>
  </p>

  {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{entry.date_added|date:'M d, Y H:i' }}
        <small><a href= "{% url "blogs:edit_entry" entry.id %}">Edit entry</a></small>
      </h4>
      <div class="card-body">
        {{entry.text|linebreaks}}
      </div>
    </div>
  {%empty%}
    <p>There are no entries for this blog yet.</p>
  {% endfor %}

{% endblock content %}

blogs/templates/blogs/blogs.html
{% extends "blogs/base.html" %}

{% block page_header %}
  <h1>Blogs</h1>
{% endblock page_header %}

{% block content %}
  <ul>
    {% for blog in blogs %}
      <li><h3>
        <a href="{% url 'blogs:blog' blog.id %}">{{blog}}</a>
      </h3></li>
    {%empty%}
      <li><h3>No blogs have been added yet.</h3></li>
    {% endfor %}
  </ul>
  
  <h3><a href="{% url 'blogs:new_blog' %}">Add a new blog:</a><h3>

{% endblock content %}

blogs/templates/blogs/edit_entry.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2><a href="{% url "blogs:blog" blog.id %}">{{blog}}</a></h2>
  <h2>Edit entry:</h2>
{% endblock page_header %}

{% block content %}
<form method='post' action="{% url "blogs:edit_entry" entry.id %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary"> Save changes</button>
    {% endbuttons %}
</form>
{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block page_header %}
  <div class='jumbotron'>
    <h1 class="display-4">Run your own blog.</h1>

    <p class="lead">Create your own blog! Write posts and create new discussion topics!</p>
    
    <a class="btn btn-lg btn-primary" href="{% url "users:register" %}"
        role="button">Register &raquo;</a>
  </div>
{% endblock page_header %}

blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>Add a new blog:</h2>
{% endblock page_header %}

{% block content %}
  <form method='post' action="{% url 'blogs:new_blog' %}" class='form'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Add blog</button>
    {% endbuttons %}
  </form>
{% endblock content %}

blogs/templates/blogs/new_entry.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}


{% block page_header %}
<h2><a href="{% url "blogs:blog" blog.id %}">{{blog}}</a></h2>
<h2>Add a new entry:</h2>
{% endblock page_header %}

{% block content %}
  <form method='post' action="{% url "blogs:new_entry" blog.id %}"
  class='form'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Add entry</button>
    {% endbuttons %}
</form>
{% endblock content %}